export const BADGE_TYPES = {
	PRIMARY: "PRIMARY",
	SECONDARY: "SECONDARY",
	WARNING: "WARNING",
	DANGER: "DANGER",
	SUCCESS: "SUCCESS",
	INFO: "INFO",
	DARK: "DARK",
	LIGHT: "LIGHT",
	WHITE: "WHITE",
}
